language: shell
os:
  - linux
#  - osx
#  - windows
#julia:
#  - 1.0
#  - 1.1
#  - nightly
script:
  - |
      if [ "${TRAVIS_DIST}" = "precise" ]; then
        sudo sh -c 'echo "foreign-architecture i386" > /etc/dpkg/dpkg.cfg.d/multiarch'
      else
        sudo dpkg --add-architecture i386
      fi
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
  - mkdir -p ${TRAVIS_HOME}/julia
  - curl -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x86/1.0/julia-1.0-latest-linux-i686.tar.gz' | tar -C ${TRAVIS_HOME}/julia -x -z --strip-components=1 -f -
  - ls ${TRAVIS_HOME}
  - ls ${TRAVIS_HOME}/julia
  - ls ${TRAVIS_HOME}/julia/bin
  - ldd ${TRAVIS_HOME}/julia/bin/julia
  - export PATH="${PATH}:${TRAVIS_HOME}/julia/bin"
  - julia --color=yes -e 'using InteractiveUtils; versioninfo()'
  - julia --color=yes --project=. -e 'using Pkg; Pkg.build()'
  - julia --color=yes --project=. -e 'using Pkg; Pkg.test()'
notifications:
  email: false
#after_success:
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
