language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
  - arm64
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
